springProfileNames:
  - BlackListGenerator
springProfileClasses:
  - com.tgt.search.microservices.blackList.config.BlackListGeneratorSpringConfig

appConfigClass: com.tgt.search.microservices.blackList.config.BlackListGeneratorAppConfig

databaseConfig:
    host: localhost
    port: 5432
    activeDB: BlackListDB
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    initDatabase: true

blackListKeywordConfig:
    blackListEligibleThreshold: 
    blackListEligibleThresholdPercentage: 

server:
  applicationConnectors:
    - port: 9090
      type: http
  adminConnectors:
    - port: 9091
      type: http
  requestLog:
    appenders:
      - type: file
        threshold: INFO
        logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
        currentLogFilename: /tmp/request.log
        archivedLogFilenamePattern: /tmp/request.%d.log.gz
        archivedFileCount: 10
        timeZone: UTC