CREATE SEQUENCE IF NOT EXISTS optout_id_seq;
CREATE TABLE IF NOT EXISTS OPTOUTKEYWORDENTITY
(
    SERIALID INT NOT NULL,
    OPTOUTKEYWORD VARCHAR(100) NOT NULL,
    KEYWORDFREQUENCY INT NOT NULL,
    UPDATEDTIME TIMESTAMP,
    PRIMARY KEY (SERIALID)
);
ALTER SEQUENCE optout_id_seq OWNED BY OPTOUTKEYWORDENTITY.SERIALID;
alter table OPTOUTKEYWORDENTITY alter column SERIALID set default nextval('optout_id_seq');

CREATE SEQUENCE IF NOT EXISTS blacklist_id_seq;
CREATE TABLE IF NOT EXISTS BLACKLISTKEYWORDENTITY
(
    SERIALID INT NOT NULL,
    BLACKLISTKEYWORD VARCHAR(100) NOT NULL,
    UPDATEDTIME DATE,
    PRIMARY KEY (SERIALID)
);
ALTER SEQUENCE blacklist_id_seq OWNED BY BLACKLISTKEYWORDENTITY.SERIALID;
alter table BLACKLISTKEYWORDENTITY alter column SERIALID set default nextval('blacklist_id_seq');
